# Use a small official Nginx image
FROM nginx:alpine

# Copy game file into the default nginx web directory
COPY index.html /usr/share/nginx/html/index.html

# Expose port 80
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
